# SPRING_PROFILES_ACTIVE=int

spring:
  datasource:
    url: ${DATABASE_URL}
    username:
    password:
    platform: postgres
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
